# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'


source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org'
source 'https://git2.baijiashilian.com/open-ios/specs.git'
target 'iosApp' do
# Comment the next line if you don't want to use dynamic frameworks
# use_frameworks! #:linkage => :static
use_frameworks! :linkage => :dynamic

inhibit_all_warnings!
# Pods for iosApp
 pod 'composeApp', :path => '../composeApp/'
# pod 'TXLiteAVSDK_TRTC', '12.0.16292'
pod 'Protobuf', '3.22.4'

pod 'SVGAPlayer', '~> 2.3'
pod 'SDWebImage'
pod 'UMCommon', '7.5.0'
pod 'UMDevice'
pod 'QCloudCOSXML/Transfer'
pod 'AFNetworking'
pod 'iosMath', '~> 0.9'

pod 'DTFoundation'
pod 'FinApplet'
pod 'Bugly'
pod 'BJLLog', '~> 3.7.4.6'
pod 'BaijiaYun/_BJLiveUIBigClass', '4.18.0'
pod 'BaijiaYun/_BJLiveUISmallClass', '4.18.0'
pod 'BaijiaYun/_BJLiveUIBase', '4.18.0'
pod 'BaijiaYun/_BJLiveUIEE', '4.18.0'
pod 'BJLiveBase', '4.18.0'
pod 'BaijiaYun/_BJLSellUI', '4.18.0'
pod 'BaijiaYun/_BJLiveCore', '4.18.0'
pod 'BaijiaYun/_BJPlaybackUI', '4.18.0'
pod 'BaijiaYun/BJVideoPlayerCore', '4.18.0'
pod 'BaijiaYun/BJPlayerUIBase', '4.18.0'
pod 'DTCoreText', :git => "https://github.com/vickyleu/DTCoreText.git",branch: 'develop'
#
# pod 'PLVImagePickerController', '0.1.3'
# pod 'PLVLiveScenesSDK', '1.19.1'
pod 'polyv', :git => 'https://github.com/vickyleu/polyvmultiplatform.git', branch: 'main'
#
# pod 'VIMediaCache', :git => 'https://github.com/vickyleu/VIMediaCache.git', branch: 'master'
end

puts "首次执行前请先确认是否已执行此命令 brew install xcode-kotlin &xcode-kotlin install"
post_install do |installer|
 # 定义需要删除的 Framework 路径
 paths_to_remove = [
 "Pods/PLVLiveScenesSDK/Frameworks/MiniFramework",
 "Pods/PLVFoundationSDK/Frameworks/MiniFramework",
 "Pods/PLVBusinessSDK/Frameworks/MiniFramework"
 ]
# # 移除文件的 CocoaPods 引用，避免后续检查
# installer.pod_targets.each do |pod_target|
# pod_target.file_accessors.each do |file_accessor|
# paths_to_remove.each do |path|
# file_accessor.vendored_frameworks.reject! { |framework| framework.to_s.start_with?(path) }
# end
# end
# end

 # 执行删除操作
 paths_to_remove.each do |path|
 if File.exist?(path)
 FileUtils.rm_rf(path)
 puts "Removed #{path}"
 end
 end


installer.pods_project.build_configurations.each do |config|
 config.build_settings.delete 'EXCLUDED_ARCHS[sdk=iphonesimulator*]'
 config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
end
installer.pods_project.targets.each do |target|
 # 只处理 PBXNativeTarget 和 PBXAggregateTarget
 next unless target.is_a?(Xcodeproj::Project::Object::PBXNativeTarget) || target.is_a?(Xcodeproj::Project::Object::PBXAggregateTarget)
 # 判断是否是 Swift 项目
 is_swift_target = false
 if target.is_a?(Xcodeproj::Project::Object::PBXNativeTarget)
 is_swift_target = target.source_build_phase&.files&.any? do |file|
 file.file_ref.path.end_with?('.swift')
 end
 end


target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = "5.0"
if config.base_configuration_reference
 # config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
 config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
# config.build_settings.delete 'ONLY_ACTIVE_ARCH'
if config.name == 'Debug'
 # Debug 环境
 config.build_settings.delete 'ONLY_ACTIVE_ARCH'
 config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
 elsif config.name == 'Release'
 # Release 环境
 config.build_settings.delete 'ONLY_ACTIVE_ARCH'
 config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
 end

# config.build_settings['ONLY_ACTIVE_ARCH'] = "NO"
end
 config.build_settings.delete 'VALID_ARCHS'
 config.build_settings.delete 'EXCLUDED_ARCHS[sdk=iphonesimulator*]'
 config.build_settings.delete 'DEBUG_INFORMATION_FORMAT'
 config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

xcconfig_path = config.base_configuration_reference.real_path
xcconfig = File.read(xcconfig_path)
xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

# config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = 'YES'
# Disable signing for all synthetic pods KT-54314
config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
config.build_settings['CODE_SIGNING_IDENTITY'] = ""
end
end
end
